package org.example;

public class Main {
    public static void main(String[] args) {
        String author = "D";
        Generator generator = new GeneratorJava();
        String result = generator
                .createSomeText("// generated by " + author)
                .createClass("Main", Modificator.PUBLIC)
                .createField("a", 1, Type.INT, Modificator.PRIVATE)
                .createField("b", 1, Type.INT, Modificator.PRIVATE)
                .generate();
        System.out.println(result);
    }
}